apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-service.fullname" . }}-config
  labels:
    {{- include "hello-service.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.nodeEnv }}
  APP_VERSION: {{ .Values.app.version | quote }}
